### ISSUE TITLE
Problem building docker container

### ISSUE THREAD

**Issue by jblakley** [dessa-public/DeepFake-Detection#16]
I am trying to replicate test but it is failing at
`nvidia-docker build . -t atlas_ff`

at the command:
`RUN pip install -v --no-cache-dir apex/`

I am running on an Azure NC6_Promo instance with Ubuntu 18.04 and NVIDIA K80. Running python 3.6.12 in a conda environment.  `nvidia-smi` output at end of this post. I could successfully install apex on the host instance but the docker build is failing. Help!

Error is:

`Processing ./apex
  Created temporary directory: /tmp/pip-req-build-2yeom3ry
  Added file:///workspace/apex to build tracker '/tmp/pip-req-tracker-odo6vywe'
    Running setup.py (path:/tmp/pip-req-build-2yeom3ry/setup.py) egg_info for package from file:///workspace/apex
    Created temporary directory: /tmp/pip-pip-egg-info-95qvevi0
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-2yeom3ry/setup.py", line 35, in <module>
        _, bare_metal_major, _ = get_cuda_bare_metal_version(cpp_extension.CUDA_HOME)
      File "/tmp/pip-req-build-2yeom3ry/setup.py", line 14, in get_cuda_bare_metal_version
        raw_output = subprocess.check_output([cuda_dir + "/bin/nvcc", "-V"], universal_newlines=True)
    TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'`

    Warning: Torch did not find available GPUs on this system.
     If your intention is to cross-compile, this is not an error.
    By default, Apex will cross-compile for Pascal (compute capabilities 6.0, 6.1, 6.2),
    Volta (compute capability 7.0), Turing (compute capability 7.5),
    and, if the CUDA version is >= 11.0, Ampere (compute capability 8.0).
    If you wish to cross-compile for a single specific architecture,
    export TORCH_CUDA_ARCH_LIST="compute capability" before running setup.py.

`ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 228, in _main
    status = self.run(options, args)
  File "/opt/conda/lib/python3.6/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/opt/conda/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 324, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/opt/conda/lib/python3.6/site-packages/pip/_internal/resolution/legacy/resolver.py", line 183, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/opt/conda/lib/python3.6/site-packages/pip/_internal/resolution/legacy/resolver.py", line 388, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/opt/conda/lib/python3.6/site-packages/pip/_internal/resolution/legacy/resolver.py", line 340, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/opt/conda/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 483, in prepare_linked_requirement
    req, self.req_tracker, self.finder, self.build_isolation,
  File "/opt/conda/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 91, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/opt/conda/lib/python3.6/site-packages/pip/_internal/distributions/sdist.py", line 40, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/opt/conda/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 555, in prepare_metadata
    self.metadata_directory = self._generate_metadata()
  File "/opt/conda/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 535, in _generate_metadata
    details=self.name or "from {}".format(self.link)
  File "/opt/conda/lib/python3.6/site-packages/pip/_internal/operations/build/metadata_legacy.py", line 73, in generate_metadata
    command_desc='python setup.py egg_info',
  File "/opt/conda/lib/python3.6/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

`+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.87.01    Driver Version: 418.87.01    CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           On   | 00000001:00:00.0 Off |                    0 |
| N/A   49C    P8    28W / 149W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
`

**Comment by jblakley** [comment]
This issue seems to be gone.
