### ISSUE TITLE
CMake must be installed to build the following extensions: dlib

### ISSUE THREAD

**Issue by ak-kuznetsov** [dessa-public/DeepFake-Detection#22]
> (conda) alex@G5-5587:~/DeepFake-Detection/custom_docker_image$ nvidia-docker build . -t atlas_ff
> Sending build context to Docker daemon  1.942MB
> Step 1/15 : FROM pytorch/pytorch:1.3-cuda10.1-cudnn7-runtime
>  ---> ba2da111b833
> Step 2/15 : LABEL maintainer "NVIDIA CORPORATION <cudatools@nvidia.com>"
>  ---> Using cache
>  ---> 1778b16c889e
> Step 3/15 : RUN  apt-get update   && apt-get install -y wget git libsm6 libxext6 libxrender-dev libgtk2.0-dev   && rm -rf /var/lib/apt/lists/*
>  ---> Using cache
>  ---> 0474a3577e36
> Step 4/15 : RUN apt-get update    && apt-get upgrade -y     && apt-get install bzip2
>  ---> Using cache
>  ---> 703132040c49
> Step 5/15 : RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
>  ---> Using cache
>  ---> 4b283d8d79b1
> Step 6/15 : RUN bash miniconda.sh -b -p /miniconda
>  ---> Using cache
>  ---> 73cd40916b1a
> Step 7/15 : RUN /bin/bash -c "source ~/.bashrc"
>  ---> Using cache
>  ---> 26aa20bb0b99
> Step 8/15 : RUN conda init
>  ---> Using cache
>  ---> 8b9a20aba2bc
> Step 9/15 : RUN /bin/bash -c "source ~/.bashrc"
>  ---> Using cache
>  ---> 77e20334a1d7
> Step 10/15 : RUN conda remove -c anaconda pyyaml -y
>  ---> Using cache
>  ---> d361c1c04368
> Step 11/15 : COPY requirements.txt /tmp
>  ---> Using cache
>  ---> f797667b3857
> Step 12/15 : RUN pip install --no-cache-dir -r /tmp/requirements.txt         && rm /tmp/requirements.txt
>  ---> Running in 59d72d57cd2f
> Collecting numpy==1.17.3
>   Downloading numpy-1.17.3-cp36-cp36m-manylinux1_x86_64.whl (20.0 MB)
> Collecting dlib==19.15.0
>   Downloading dlib-19.15.0.tar.gz (3.3 MB)
> Collecting pathlib==1.0.1
>   Downloading pathlib-1.0.1.tar.gz (49 kB)
> Collecting Pillow==6.2.0
>   Downloading Pillow-6.2.0-cp36-cp36m-manylinux1_x86_64.whl (2.1 MB)
> Collecting tqdm==4.25.0
>   Downloading tqdm-4.25.0-py2.py3-none-any.whl (43 kB)
> Collecting scikit-learn==0.21.3
>   Downloading scikit_learn-0.21.3-cp36-cp36m-manylinux1_x86_64.whl (6.7 MB)
> Collecting matplotlib==3.1.1
>   Downloading matplotlib-3.1.1-cp36-cp36m-manylinux1_x86_64.whl (13.1 MB)
> Requirement already satisfied: requests in /opt/conda/lib/python3.6/site-packages (from -r /tmp/requirements.txt (line 8)) (2.24.0)
> Collecting jsonschema==3.0.2
>   Downloading jsonschema-3.0.2-py2.py3-none-any.whl (54 kB)
> Collecting dill==0.2.8.2
>   Downloading dill-0.2.8.2.tar.gz (150 kB)
> Collecting google-api-python-client==1.7.3
>   Downloading google_api_python_client-1.7.3-py2.py3-none-any.whl (55 kB)
> Collecting google-auth-httplib2==0.0.3
>   Downloading google_auth_httplib2-0.0.3-py2.py3-none-any.whl (6.3 kB)
> Collecting google-cloud-storage==1.10.0
>   Downloading google_cloud_storage-1.10.0-py2.py3-none-any.whl (52 kB)
> Collecting PyYAML==5.1.2
>   Downloading PyYAML-5.1.2.tar.gz (265 kB)
> Collecting freezegun==0.3.12
>   Downloading freezegun-0.3.12-py2.py3-none-any.whl (12 kB)
> Collecting flask-restful==0.3.7
>   Downloading Flask_RESTful-0.3.7-py2.py3-none-any.whl (24 kB)
> Collecting Flask==1.1.1
>   Downloading Flask-1.1.1-py2.py3-none-any.whl (94 kB)
> Collecting Flask-Cors==3.0.8
>   Downloading Flask_Cors-3.0.8-py2.py3-none-any.whl (14 kB)
> Collecting pandas==0.23.3
>   Downloading pandas-0.23.3-cp36-cp36m-manylinux1_x86_64.whl (8.9 MB)
> Collecting promise==2.2.1
>   Downloading promise-2.2.1.tar.gz (19 kB)
> Collecting redis==3.3.11
>   Downloading redis-3.3.11-py2.py3-none-any.whl (66 kB)
> Collecting slackclient==1.3.0
>   Downloading slackclient-1.3.0-py2.py3-none-any.whl (18 kB)
> Collecting Werkzeug==0.16.0
>   Downloading Werkzeug-0.16.0-py2.py3-none-any.whl (327 kB)
> Collecting boto3==1.9.86
>   Downloading boto3-1.9.86-py2.py3-none-any.whl (128 kB)
> Collecting boto==2.49.0
>   Downloading boto-2.49.0-py2.py3-none-any.whl (1.4 MB)
> Collecting python-jose==3.0.1
>   Downloading python_jose-3.0.1-py2.py3-none-any.whl (25 kB)
> Collecting python-keycloak==0.17.6
>   Downloading python-keycloak-0.17.6.tar.gz (18 kB)
> Collecting tabulate==0.8.3
>   Downloading tabulate-0.8.3.tar.gz (46 kB)
> Collecting docker==4.0.2
>   Downloading docker-4.0.2-py2.py3-none-any.whl (138 kB)
> Collecting joblib>=0.11
>   Downloading joblib-1.0.1-py3-none-any.whl (303 kB)
> Collecting scipy>=0.17.0
>   Downloading scipy-1.5.4-cp36-cp36m-manylinux1_x86_64.whl (25.9 MB)
> Collecting kiwisolver>=1.0.1
>   Downloading kiwisolver-1.3.1-cp36-cp36m-manylinux1_x86_64.whl (1.1 MB)
> Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1
>   Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
> Collecting cycler>=0.10
>   Downloading cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
> Collecting python-dateutil>=2.1
>   Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
> Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /opt/conda/lib/python3.6/site-packages (from requests->-r /tmp/requirements.txt (line 8)) (1.25.11)
> Requirement already satisfied: idna<3,>=2.5 in /opt/conda/lib/python3.6/site-packages (from requests->-r /tmp/requirements.txt (line 8)) (2.10)
> Requirement already satisfied: chardet<4,>=3.0.2 in /opt/conda/lib/python3.6/site-packages (from requests->-r /tmp/requirements.txt (line 8)) (3.0.4)
> Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.6/site-packages (from requests->-r /tmp/requirements.txt (line 8)) (2020.6.20)
> Requirement already satisfied: six>=1.11.0 in /opt/conda/lib/python3.6/site-packages (from jsonschema==3.0.2->-r /tmp/requirements.txt (line 9)) (1.15.0)
> Collecting pyrsistent>=0.14.0
>   Downloading pyrsistent-0.18.0-cp36-cp36m-manylinux1_x86_64.whl (117 kB)
> Requirement already satisfied: setuptools in /opt/conda/lib/python3.6/site-packages (from jsonschema==3.0.2->-r /tmp/requirements.txt (line 9)) (50.3.0.post20201006)
> Collecting attrs>=17.4.0
>   Downloading attrs-21.2.0-py2.py3-none-any.whl (53 kB)
> Collecting httplib2<1dev,>=0.9.2
>   Downloading httplib2-0.19.1-py3-none-any.whl (95 kB)
> Collecting google-auth>=1.4.1
>   Downloading google_auth-1.32.1-py2.py3-none-any.whl (147 kB)
> Collecting uritemplate<4dev,>=3.0.0
>   Downloading uritemplate-3.0.1-py2.py3-none-any.whl (15 kB)
> Collecting google-api-core<2.0.0dev,>=0.1.1
>   Downloading google_api_core-1.31.0-py2.py3-none-any.whl (93 kB)
> Collecting google-resumable-media>=0.3.1
>   Downloading google_resumable_media-1.3.1-py2.py3-none-any.whl (75 kB)
> Collecting google-cloud-core<0.29dev,>=0.28.0
>   Downloading google_cloud_core-0.28.1-py2.py3-none-any.whl (25 kB)
> Collecting pytz
>   Downloading pytz-2021.1-py2.py3-none-any.whl (510 kB)
> Collecting aniso8601>=0.82
>   Downloading aniso8601-9.0.1-py2.py3-none-any.whl (52 kB)
> Collecting click>=5.1
>   Downloading click-8.0.1-py3-none-any.whl (97 kB)
> Collecting itsdangerous>=0.24
>   Downloading itsdangerous-2.0.1-py3-none-any.whl (18 kB)
> Collecting Jinja2>=2.10.1
>   Downloading Jinja2-3.0.1-py3-none-any.whl (133 kB)
> Collecting websocket-client<1.0a0,>=0.35
>   Downloading websocket_client-0.59.0-py2.py3-none-any.whl (67 kB)
> Collecting s3transfer<0.2.0,>=0.1.10
>   Downloading s3transfer-0.1.13-py2.py3-none-any.whl (59 kB)
> Collecting botocore<1.13.0,>=1.12.86
>   Downloading botocore-1.12.253-py2.py3-none-any.whl (5.7 MB)
> Collecting jmespath<1.0.0,>=0.7.1
>   Downloading jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
> Collecting future<1.0
>   Downloading future-0.18.2.tar.gz (829 kB)
> Collecting ecdsa<1.0
>   Downloading ecdsa-0.17.0-py2.py3-none-any.whl (119 kB)
> Collecting rsa
>   Downloading rsa-4.7.2-py3-none-any.whl (34 kB)
> Collecting pyasn1-modules>=0.2.1
>   Downloading pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
> Collecting cachetools<5.0,>=2.0.0
>   Downloading cachetools-4.2.2-py3-none-any.whl (11 kB)
> Collecting packaging>=14.3
>   Downloading packaging-21.0-py3-none-any.whl (40 kB)
> Collecting googleapis-common-protos<2.0dev,>=1.6.0
>   Downloading googleapis_common_protos-1.53.0-py2.py3-none-any.whl (198 kB)
> Collecting protobuf>=3.12.0
>   Downloading protobuf-3.17.3-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.0 MB)
> Collecting google-crc32c<2.0dev,>=1.0; python_version >= "3.5"
>   Downloading google_crc32c-1.1.2-cp36-cp36m-manylinux2014_x86_64.whl (38 kB)
> Collecting importlib-metadata; python_version < "3.8"
>   Downloading importlib_metadata-4.6.1-py3-none-any.whl (17 kB)
> Collecting MarkupSafe>=2.0
>   Downloading MarkupSafe-2.0.1-cp36-cp36m-manylinux2010_x86_64.whl (30 kB)
> Collecting docutils<0.16,>=0.10
>   Downloading docutils-0.15.2-py3-none-any.whl (547 kB)
> Collecting pyasn1>=0.1.3
>   Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
> Requirement already satisfied: cffi>=1.0.0 in /opt/conda/lib/python3.6/site-packages (from google-crc32c<2.0dev,>=1.0; python_version >= "3.5"->google-resumable-media>=0.3.1->google-cloud-storage==1.10.0->-r /tmp/requirements.txt (line 13)) (1.14.0)
> Collecting zipp>=0.5
>   Downloading zipp-3.5.0-py3-none-any.whl (5.7 kB)
> Collecting typing-extensions>=3.6.4; python_version < "3.8"
>   Downloading typing_extensions-3.10.0.0-py3-none-any.whl (26 kB)
> Requirement already satisfied: pycparser in /opt/conda/lib/python3.6/site-packages (from cffi>=1.0.0->google-crc32c<2.0dev,>=1.0; python_version >= "3.5"->google-resumable-media>=0.3.1->google-cloud-storage==1.10.0->-r /tmp/requirements.txt (line 13)) (2.20)
> Building wheels for collected packages: dlib, pathlib, dill, PyYAML, promise, python-keycloak, tabulate, future
>   Building wheel for dlib (setup.py): started
>   Building wheel for dlib (setup.py): finished with status 'error'
>   ERROR: Command errored out with exit status 1:
>    command: /opt/conda/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-eg8b9tta/dlib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-eg8b9tta/dlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-4dcee7yg
>        cwd: /tmp/pip-install-eg8b9tta/dlib/
>   Complete output (53 lines):
>   running bdist_wheel
>   running build
>   running build_py
>   package init file 'dlib/__init__.py' not found (or not a regular file)
>   running build_ext
>   Traceback (most recent call last):
>     File "/tmp/pip-install-eg8b9tta/dlib/setup.py", line 118, in get_cmake_version
>       out = subprocess.check_output(['cmake', '--version'])
>     File "/opt/conda/lib/python3.6/subprocess.py", line 356, in check_output
>       **kwargs).stdout
>     File "/opt/conda/lib/python3.6/subprocess.py", line 423, in run
>       with Popen(*popenargs, **kwargs) as process:
>     File "/opt/conda/lib/python3.6/subprocess.py", line 729, in __init__
>       restore_signals, start_new_session)
>     File "/opt/conda/lib/python3.6/subprocess.py", line 1364, in _execute_child
>       raise child_exception_type(errno_num, err_msg, err_filename)
>   FileNotFoundError: [Errno 2] No such file or directory: 'cmake': 'cmake'
>   
>   During handling of the above exception, another exception occurred:
>   
>   Traceback (most recent call last):
>     File "<string>", line 1, in <module>
>     File "/tmp/pip-install-eg8b9tta/dlib/setup.py", line 257, in <module>
>       'Topic :: Software Development',
>     File "/opt/conda/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
>       return distutils.core.setup(**attrs)
>     File "/opt/conda/lib/python3.6/distutils/core.py", line 148, in setup
>       dist.run_commands()
>     File "/opt/conda/lib/python3.6/distutils/dist.py", line 955, in run_commands
>       self.run_command(cmd)
>     File "/opt/conda/lib/python3.6/distutils/dist.py", line 974, in run_command
>       cmd_obj.run()
>     File "/opt/conda/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 290, in run
>       self.run_command('build')
>     File "/opt/conda/lib/python3.6/distutils/cmd.py", line 313, in run_command
>       self.distribution.run_command(command)
>     File "/opt/conda/lib/python3.6/distutils/dist.py", line 974, in run_command
>       cmd_obj.run()
>     File "/opt/conda/lib/python3.6/distutils/command/build.py", line 135, in run
>       self.run_command(cmd_name)
>     File "/opt/conda/lib/python3.6/distutils/cmd.py", line 313, in run_command
>       self.distribution.run_command(command)
>     File "/opt/conda/lib/python3.6/distutils/dist.py", line 974, in run_command
>       cmd_obj.run()
>     File "/tmp/pip-install-eg8b9tta/dlib/setup.py", line 127, in run
>       cmake_version = self.get_cmake_version()
>     File "/tmp/pip-install-eg8b9tta/dlib/setup.py", line 123, in get_cmake_version
>       "\n*******************************************************************\n")
>   RuntimeError:
>   *******************************************************************
>    CMake must be installed to build the following extensions: dlib
>   *******************************************************************
>   
>   ----------------------------------------
>   ERROR: Failed building wheel for dlib
>   Running setup.py clean for dlib
>   Building wheel for pathlib (setup.py): started
>   Building wheel for pathlib (setup.py): finished with status 'done'
>   Created wheel for pathlib: filename=pathlib-1.0.1-py3-none-any.whl size=14348 sha256=885ebf81f964aa087218ca21360c47a5172c8d305fd376b8de1c7da3b0b5982d
>   Stored in directory: /tmp/pip-ephem-wheel-cache-p1up0y1v/wheels/e1/32/91/afe2cabe6f77819de11759f2a07d538cd521ef3a9dd81ba0b4
>   Building wheel for dill (setup.py): started
>   Building wheel for dill (setup.py): finished with status 'done'
>   Created wheel for dill: filename=dill-0.2.8.2-py3-none-any.whl size=76450 sha256=0f4359d78bf10161226a5fa5898490ceb1f95af283c5b180340ccac4ecc20c95
>   Stored in directory: /tmp/pip-ephem-wheel-cache-p1up0y1v/wheels/b7/c6/4a/b50701e335c856eeb495d321cdbe8020386461de08b31e63d6
>   Building wheel for PyYAML (setup.py): started
>   Building wheel for PyYAML (setup.py): finished with status 'done'
>   Created wheel for PyYAML: filename=PyYAML-5.1.2-cp36-cp36m-linux_x86_64.whl size=44103 sha256=53b9059b2cd42f611c12125ffdeb243c5b9074373fc03d4de965d79c9dd10c1c
>   Stored in directory: /tmp/pip-ephem-wheel-cache-p1up0y1v/wheels/d8/9b/e7/75af463b873c119dd444151fc54a8e190c87993593e1fa194a
>   Building wheel for promise (setup.py): started
>   Building wheel for promise (setup.py): finished with status 'done'
>   Created wheel for promise: filename=promise-2.2.1-py3-none-any.whl size=21290 sha256=a6e9e0fd9d07313d9f91789201a19ac407c736acb7a4b104401eef73a2201e6c
>   Stored in directory: /tmp/pip-ephem-wheel-cache-p1up0y1v/wheels/aa/7b/df/e774aae29b66b522e411f69c9a97e2e37ab541ad877069df58
>   Building wheel for python-keycloak (setup.py): started
>   Building wheel for python-keycloak (setup.py): finished with status 'done'
>   Created wheel for python-keycloak: filename=python_keycloak-0.17.6-py3-none-any.whl size=26886 sha256=23718f53b24fe8fd697489d50d0ebb699d7041797a6158d50658dece709456ce
>   Stored in directory: /tmp/pip-ephem-wheel-cache-p1up0y1v/wheels/90/b4/44/7a78a6bdc1f263977d4b3b21bf44199b377691471b8c0a8dc0
>   Building wheel for tabulate (setup.py): started
>   Building wheel for tabulate (setup.py): finished with status 'done'
>   Created wheel for tabulate: filename=tabulate-0.8.3-py3-none-any.whl size=23377 sha256=a5b811736e9506c4930de858c505df4a488ed902e12efba23135218392756b92
>   Stored in directory: /tmp/pip-ephem-wheel-cache-p1up0y1v/wheels/20/2a/38/bbf076580de21676f282b7a40156184b9ef5bc8ebca4dbddb1
>   Building wheel for future (setup.py): started
>   Building wheel for future (setup.py): finished with status 'done'
>   Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491059 sha256=00ab083d63f2d84e330e431c8bd97065521cd5c71a6bfb3ffa73e7474bee7398
>   Stored in directory: /tmp/pip-ephem-wheel-cache-p1up0y1v/wheels/6e/9c/ed/4499c9865ac1002697793e0ae05ba6be33553d098f3347fb94
> Successfully built pathlib dill PyYAML promise python-keycloak tabulate future
> Failed to build dlib
> Installing collected packages: numpy, dlib, pathlib, Pillow, tqdm, joblib, scipy, scikit-learn, kiwisolver, pyparsing, cycler, python-dateutil, matplotlib, pyrsistent, attrs, jsonschema, dill, httplib2, pyasn1, pyasn1-modules, cachetools, rsa, google-auth, google-auth-httplib2, uritemplate, google-api-python-client, packaging, pytz, protobuf, googleapis-common-protos, google-api-core, google-crc32c, google-resumable-media, google-cloud-core, google-cloud-storage, PyYAML, freezegun, zipp, typing-extensions, importlib-metadata, click, Werkzeug, itsdangerous, MarkupSafe, Jinja2, Flask, aniso8601, flask-restful, Flask-Cors, pandas, promise, redis, websocket-client, slackclient, jmespath, docutils, botocore, s3transfer, boto3, boto, future, ecdsa, python-jose, python-keycloak, tabulate, docker
>   Attempting uninstall: numpy
>     Found existing installation: numpy 1.17.2
>     Uninstalling numpy-1.17.2:
>       Successfully uninstalled numpy-1.17.2
>     Running setup.py install for dlib: started
>     Running setup.py install for dlib: finished with status 'error'
>     ERROR: Command errored out with exit status 1:
>      command: /opt/conda/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-eg8b9tta/dlib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-eg8b9tta/dlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-low0q4rl/install-record.txt --single-version-externally-managed --compile --install-headers /opt/conda/include/python3.6m/dlib
>          cwd: /tmp/pip-install-eg8b9tta/dlib/
>     Complete output (55 lines):
>     running install
>     running build
>     running build_py
>     package init file 'dlib/__init__.py' not found (or not a regular file)
>     running build_ext
>     Traceback (most recent call last):
>       File "/tmp/pip-install-eg8b9tta/dlib/setup.py", line 118, in get_cmake_version
>         out = subprocess.check_output(['cmake', '--version'])
>       File "/opt/conda/lib/python3.6/subprocess.py", line 356, in check_output
>         **kwargs).stdout
>       File "/opt/conda/lib/python3.6/subprocess.py", line 423, in run
>         with Popen(*popenargs, **kwargs) as process:
>       File "/opt/conda/lib/python3.6/subprocess.py", line 729, in __init__
>         restore_signals, start_new_session)
>       File "/opt/conda/lib/python3.6/subprocess.py", line 1364, in _execute_child
>         raise child_exception_type(errno_num, err_msg, err_filename)
>     FileNotFoundError: [Errno 2] No such file or directory: 'cmake': 'cmake'
>     
>     During handling of the above exception, another exception occurred:
>     
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-install-eg8b9tta/dlib/setup.py", line 257, in <module>
>         'Topic :: Software Development',
>       File "/opt/conda/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
>         return distutils.core.setup(**attrs)
>       File "/opt/conda/lib/python3.6/distutils/core.py", line 148, in setup
>         dist.run_commands()
>       File "/opt/conda/lib/python3.6/distutils/dist.py", line 955, in run_commands
>         self.run_command(cmd)
>       File "/opt/conda/lib/python3.6/distutils/dist.py", line 974, in run_command
>         cmd_obj.run()
>       File "/opt/conda/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
>         return orig.install.run(self)
>       File "/opt/conda/lib/python3.6/distutils/command/install.py", line 545, in run
>         self.run_command('build')
>       File "/opt/conda/lib/python3.6/distutils/cmd.py", line 313, in run_command
>         self.distribution.run_command(command)
>       File "/opt/conda/lib/python3.6/distutils/dist.py", line 974, in run_command
>         cmd_obj.run()
>       File "/opt/conda/lib/python3.6/distutils/command/build.py", line 135, in run
>         self.run_command(cmd_name)
>       File "/opt/conda/lib/python3.6/distutils/cmd.py", line 313, in run_command
>         self.distribution.run_command(command)
>       File "/opt/conda/lib/python3.6/distutils/dist.py", line 974, in run_command
>         cmd_obj.run()
>       File "/tmp/pip-install-eg8b9tta/dlib/setup.py", line 127, in run
>         cmake_version = self.get_cmake_version()
>       File "/tmp/pip-install-eg8b9tta/dlib/setup.py", line 123, in get_cmake_version
>         "\n*******************************************************************\n")
>     RuntimeError:
>     *******************************************************************
>      CMake must be installed to build the following extensions: dlib
>     *******************************************************************
>     
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: /opt/conda/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-eg8b9tta/dlib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-eg8b9tta/dlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-low0q4rl/install-record.txt --single-version-externally-managed --compile --install-headers /opt/conda/include/python3.6m/dlib Check the logs for full command output.
> The command '/bin/sh -c pip install --no-cache-dir -r /tmp/requirements.txt         && rm /tmp/requirements.txt' returned a non-zero code: 1
>

**Comment by ak-kuznetsov** [comment]
ERROR: Failed building wheel for dlib

**Comment by ak-kuznetsov** [comment]
CMake must be installed to build the following extensions: dlib

**Comment by ak-kuznetsov** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'cmake': 'cmake'

**Comment by ak-kuznetsov** [comment]
at the last stage of the installation, these errors come out
